version: "3.3"
services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    container_name: nextjs
  e2e:
    image: cypress/included:6.2.1
    container_name: cypress
    depends_on:
      - nextjs
    environment:
      - CYPRESS_baseUrl=http://nextjs:3000
    working_dir: /e2e
    volumes:
       - .:/e2e

